#!/bin/bash 

set -euxo pipefail

rm -rf ./build

xcodebuild archive \
--scheme=wallsync \
-destination "generic/platform=macOS" \
-archivePath="./build"

cp -r ./build/Release/wallsync.app ./build

VERSION=$(cat .commitlog.release | xargs)

npx appdmg create-dmg.json "./build/wallsync-$VERSION.dmg"



